version: '3'
services:

  node-trilla:
    build: ./docker/node
    ports:
      - 3000:3000
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html

  mysql-trilla:
    image: mysql:5.7
    command: ['--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=app
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=app
    ports:
      - 3306:3306
      
  adminer-trilla:
    image: adminer
    restart: always
    ports:
      - 8082:8080